# Generated by Django 5.2.6 on 2025-09-22 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationConfigurations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.CharField(choices=[('OPENAI', 'OPENAI'), ('OLLAMA', 'OLLAMA'), ('GEMINI', 'GEMINI')], default='OPENAI', max_length=20)),
                ('ai_model_api_key', models.CharField(blank=True, help_text='AI Model API key', max_length=255, null=True)),
                ('google_client_id', models.CharField(blank=True, help_text='Google Client ID', max_length=255, null=True)),
                ('google_client_secret', models.CharField(blank=True, help_text='Google client secret', max_length=255, null=True)),
                ('firecrawl_api_key', models.CharField(blank=True, help_text='FC API key', max_length=255, null=True)),
                ('slack_client_id', models.CharField(blank=True, help_text='Slack Client ID', max_length=255, null=True)),
                ('slack_client_secret', models.CharField(blank=True, help_text='Slack client secret', max_length=255, null=True)),
                ('hubspot_client_id', models.CharField(blank=True, help_text='Hubspot Client ID', max_length=255, null=True)),
                ('hubspot_client_secret', models.CharField(blank=True, help_text='Hubspot client secret', max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserAIModelConfig',
        ),
    ]
