# Generated by Django 5.2.6 on 2025-09-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organizationconfigurations_delete_useraimodelconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationconfigurations',
            options={'verbose_name': 'Organization Configurations'},
        ),
    ]
