# Generated by Django 5.2.6 on 2025-09-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_organizationconfigurations_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationconfigurations',
            options={'verbose_name': 'Organization Configuration'},
        ),
    ]
