# Generated by Django 5.2.6 on 2025-09-22 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(default=dict)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='campaigns.lead')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.sequencestep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to='campaigns.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
