# Generated by Django 5.2.6 on 2025-09-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
