# Generated by Django 5.2.6 on 2025-11-15 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_leademail_and_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leademail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
